version: "3.9"

services:
  ui:
    build: ./UI
    container_name: ui_service
    ports:
      - "5000:5000"
    volumes:
      - dbdata:/data
    depends_on:
      - db

  db:
    build: ./DB
    container_name: db_service
    volumes:
      - dbdata:/data
    command: sleep infinity

volumes:
  dbdata:

